### PR TITLE
Add Docker build, CI workflow and documentation

### PR DESCRIPTION
**Pull request by clezag**
Hi, we're considering using your converter for a project of ours.
We're relying heavily on docker, so I've packaged the application as a container and added a basic workflow to automatically build and publish the image.
I think this could benefit all users since they don't have to set up python or install dependencies manually anymore.

I've also added a `requirements.txt` file to pin dependencies, and allow install with a `pip install -r requirements.txt`. Maybe this could be added to the README as well.

Let me know if this can be of use to you, or if you have any feedback regarding the changes.

If you want to test the image first, you can use [our build](https://github.com/noi-techpark/GTFS2NeTEx-converter/pkgs/container/gtfs2netex-converter)

### CODE REVIEW

**Comment by clezag** [comment]
@fabiograssoLD just tagging you, because sometimes github does not notify maintainers about PRs

**Comment by RMartinelliLD** [comment]
@clezag I've tested your image and built my own: everything works fine. 
Your work is a welcome addition to GTFS2NeTEx-converter.

**Comment by clezag** [comment]
@RMartinelliLD Thanks!

The build action completed successfully, but I don't see the package linked on your repo yet, it should show up on the right like this:
image

I also get an unauthorized error when trying to run
```sh
$ docker run ghcr.io/liguria-digitale/gtfs2netex-converter:latest
Unable to find image 'ghcr.io/liguria-digitale/gtfs2netex-converter:latest' locally
docker: Error response from daemon: Head "https://ghcr.io/v2/liguria-digitale/gtfs2netex-converter/manifests/latest": unauthorized.
```
Could it be that the package is set to private or do you have packages turned off on organization/repo level?

**Comment by RMartinelliLD** [comment]
@clezag I noticed this: it's an issue on organization level; I contacted the administrator to address it.

**Comment by fabiograssoLD** [comment]
Pls check now

Da: Roberto Martinelli ***@***.***>
Inviato: giovedì 19 dicembre 2024 09:30
A: Liguria-Digitale/GTFS2NeTEx-converter ***@***.***>
Cc: Grasso Fabio ***@***.***>; Mention ***@***.***>
Oggetto: Re: [Liguria-Digitale/GTFS2NeTEx-converter] Add Docker build, CI workflow and documentation (PR #2)

Questa email arriva da un mittente insolito. Assicurati che sia qualcuno di cui ti fidi.


@clezag<https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2Fclezag&e=cbfae827&h=b3e69921&f=y&p=y> I noticed this: it's an issue on organization level; I contacted the administrator to address it.

**Pull request merged**
